before_install:
  - sudo add-apt-repository ppa:sauce/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install flvtool2 -y
matrix:
  include:
    - os: linux
      env: NODE_VERSION=4
    - os: linux
      env: NODE_VERSION=5
    - os: linux
      env: NODE_VERSION=6
script:
  - tools/test-travis.sh
addons:
  apt:
    packages:
    - wget
    - tar
    - bzip2
